runner_params:
  # output keys
  fake_logits_output_key: &fake_logits "fake_logits"
  real_logits_output_key: &real_logits "real_logits"
  # phases
  generator_train_phase: &generator_train_phase generator_train
  discriminator_train_phase: &discriminator_train_phase discriminator_train


stages:

  criterion_params:
    _key_value: True
    loss_generator:
      criterion: HingeLossGenerator
    loss_discriminator:
      criterion: HingeLossDiscriminator
    loss_discriminator_real:  # only metric
      criterion: HingeLossDiscriminatorReal
    loss_discriminator_fake:  # only metric
      criterion: HingeLossDiscriminatorFake

#  callbacks_params:

    # TODO: add average prob metrics for fake & real data
#    discriminator_acc_real:
#      # no wrapper?
#      callback: AccuracyCallback
#      prefix: "discriminator_metrics/real_acc"
#      input_key: *real_targets
#      output_key: *real_logits
#      activation: "Sigmoid"
#      threshold: 0.5
#
#    discriminator_acc_fake:
#      # no wrapper?
#      callback: AccuracyCallback
#      prefix: "discriminator_metrics/fake_acc"
#      input_key: *fake_targets
#      output_key: *fake_logits
#      activation: "Sigmoid"
#      threshold: 0.5
#
#    discriminator_acc:
#      # no wrapper?
#      callback: MetricAggregationCallback
#      prefix: "discriminator_metrics/full_acc"
#      mode: "mean"
#      metrics:
#        - "discriminator_metrics/real_acc01"
#        - "discriminator_metrics/fake_acc01"