# data params ###########
image_side: 64

# model params ##########
noise_dim: 100

# evaluation params #####
#_images_support: 200

# training params #######
batch_size: 128
num_epochs: 100
# loss function #########
loss: "bce"
# optimizer params ######
# use with tstatic_choise
optim_choise: "C"

# use with tstatic
#optim_lr_G: 0.0002
#optim_beta1_G: 0.5
#optim_beta2_G: 0.999
#
#optim_lr_D: 0.0002
#optim_beta1_D: 0.5
#optim_beta2_D: 0.999
#
#steps_D: [1, 2, 3, 4, 5] # 1 for choice_C
#steps_G: [1, 2, 3, 4, 5] # 1 for choice_C
