# data params ###########
image_side: 64

# model params ##########
noise_dim: 100

# evaluation params #####
#_images_support: 200

# training params #######
batch_size: 128
num_epochs: 25
# loss function #########
loss: "bce"
# optimizer params ######
# use with tstatic_choise
optim_choise: "C"

# dynamic config
opt_dyn_D_batch_metric: "discr_proba/diff"
opt_dyn_G_batch_metric: "discr_proba/diff"
opt_dyn_D_threshold: [0.5, 0.8]
opt_dyn_G_threshold: [0.1, 0.2, 0.3]
steps_D: 5
steps_G: 5
opt_dyn_D_alpha: 1
opt_dyn_G_alpha: 1
