hparams:
  # how many images are used for perceptual metrics computation
  _images_support: &support {{_images_support or 200}}

runner_params:
  # input keys
  # Note: for albumentations transforms we have to have key "image" =(
  data_input_key: &real_data "image"
  fake_data_output_key: &fake_data "fake_image"

model_params:
  _key_value: True
  feature_extractor: # todo check if correct
    model: InceptionV3
    output_blocks: [3]
    normalize_input: False
    use_fid_inception: True


stages:

  callbacks_params:
    ######################################
    # Unconditional metrics callbacks: ###
    ######################################
    # TODO (important; low priority; usability) - how to compress this 100 lines to a reasonable amount (ideally single callback)?

    # save generated and real images
    memorizer:
      callback: MemoryAccumulatorCallback
      input_key:
        *real_data: &memory_real_data "real_data"
      output_key:
        *fake_data: &memory_fake_data "fake_data"
      memory_size: *support

    # extract inception features from real data
    feature_extractor_real:
      callback: MemoryFeatureExtractorCallback
      memory_key: *memory_real_data
      model_key: "feature_extractor"
      channels: 3
      layer_key:
        blocks.3: &memory_real_features "real_features"
        "":
          activation:
            name: "softmax"
            dim: -1
          memory_out_key: &memory_real_probabilities "real_probabilities"

    # extract inception features from fake data
    feature_extractor_fake:
      callback: MemoryFeatureExtractorCallback
      memory_key: *memory_fake_data
      model_key: "feature_extractor"
      channels: 3
      layer_key:
        blocks.3: &memory_fake_features "fake_features"
        "":
          activation:
            name: "softmax"
            dim: -1
          memory_out_key: &memory_fake_probabilities "fake_probabilities"

    distance_real_real_px:
      callback: MemoryTransformCallback
      batch_transform: RealFakeDistanceBatchTransform
      transform_in_key:
        *memory_real_data: X_real
        *memory_fake_data: X_fake
      transform_out_key: "D_px"
      suffixes: ["rr", "rf", "ff"]

    # scores on raw pixel data

    knn_scores:
      callback: MemoryMultiMetricCallback
      prefix: "metrics/knn"
      suffixes: ["acc", "acc_real", "acc_fake"]
      metric: KnnScores
      memory_key:
        D_px_rr: D_XX
        D_px_rf: D_XY
        D_px_ff: D_YY
      # metric_kwargs:
      k: 1

    frechet_inception_distance_px:
      callback: MemoryMetricCallback
      memory_key:
        *memory_fake_data: samples_a
        *memory_real_data: samples_b
      prefix: "metrics/FID_px"
      metric: "FrechetInceptionDistance"

    # scores on conv feature data

    inception_score_conv:
      callback: MemoryMetricCallback
      memory_key:
        *memory_fake_probabilities: samples
      prefix: "metrics/IS"
      metric: "InceptionScore"

    mode_score_conv:
      callback: MemoryMetricCallback
      memory_key:
        *memory_fake_probabilities: samples
        *memory_real_probabilities: samples_real
      prefix: "metrics/MS"
      metric: "ModeScore"

    frechet_inception_distance_conv:
      callback: MemoryMetricCallback
      memory_key:
        *memory_fake_features: samples_a
        *memory_real_features: samples_b
      prefix: "metrics/FID"
      metric: "FrechetInceptionDistance"

    ##############################
    # Metric callbacks [end] #####
    ##############################
