# render with:
# python catalyst_ext/rendering.py -t gan_example/tconfigs/config_base.yml gan_example/tconfigs/eval/inception/fid.yml gan_example/tconfigs/data/FFHQ.yml gan_example/tconfigs/tloss.yml gan_example/tconfigs/model/r64/dcgan.yml gan_example/tconfigs/optim/tstatic_choise.yml -n base eval data loss model optim -p gan_example/experiments_setup/params_dcgan.yml --out_dir gan_example/rendered/ffhq/r64/dcgan_optim_C_losses
# ./gan_example/rendered/ffhq/r64/dcgan_optim_C_losses/run_command_check.txt
# ./gan_example/rendered/ffhq/r64/dcgan_optim_C_losses/run_command.txt
# data params ###########
image_side: 64

# model params ##########
noise_dim: 100

# evaluation params #####
#_images_support: 200

# training params #######
batch_size: 128
num_epochs: 100
# loss function #########
loss: ["hinge", "bce", "wasserstein", "wasserstein_gp"]
# optimizer params ######
# use with tstatic_choise
optim_choise: "C"
