# data params ###########
image_side: 64

# model params ##########
noise_dim: 128
ngf: 256
ndf: 256

# evaluation params #####
#_images_support: 200

# training params #######
batch_size: 64
num_epochs: 15
# loss function #########
loss: "bce"
# optimizer params ######
# use with tstatic_choise
optim_choise: "C"
